### ISSUE TITLE
Images are cut!

### ISSUE THREAD

**Issue by fransbrain** [cloudybasement/fran.cool#27]
Oh no! What is wrong? hahaha LOL cat. So some of the images are getting cut, like the second one on the project called "Australian Association Cystic Fibrosis", can we change the oject-fit to contain instead of cover? Thonks

**Comment by fransbrain** [comment]
Another one is having two images side by side, see the page "Sakana Tengoku" for reference. Thonks @cloudybasement

**Comment by cloudybasement** [comment]
fixed
