### ISSUE TITLE
Text overlay

### ISSUE THREAD

**Issue by fransbrain** [cloudybasement/fran.cool#35]
After some scrolling, the text in the about section overlays on top of the title, can we avoid that pls?
![Screen Shot 2022-10-18 at 15 56 34](https://user-images.githubusercontent.com/116001537/196450521-9d2c6bdb-e180-4620-a74c-dafc76129ac0.png)

**Comment by cloudybasement** [comment]
we can
- Make the parallax effect slower
or
- start the text off higher
