### ISSUE TITLE
Letter spacing 

### ISSUE THREAD

**Issue by fransbrain** [cloudybasement/fran.cool#37]
Can we add some letter spacing to the titles in the project pages? 20 would be great. Merci.

**Comment by cloudybasement** [comment]
only on project pages? or everywhere the font is used?

**Comment by cloudybasement** [comment]
also 20 what? i'm guessing not 20em @fransbrain

**Comment by fransbrain** [comment]
Well when I inspected i put 20, what is the base unit you used? 
And it only looked too tight in the titles of the project pages, the other ones are single words and seem fine to me. what do u think?

**Comment by cloudybasement** [comment]
<img width="159" alt="20221018173833" src="https://user-images.githubusercontent.com/43254977/196477640-c8980d38-a096-47b3-b7d8-812ef83bc14b.png">
In my Chrome DevTools Inspector it just rejects it without a unit, no idea where you put 20
I put it at `.04em` for now

**Comment by fransbrain** [comment]
do we have different chromes hahahaah
