### ISSUE TITLE
visit link visibility

### ISSUE THREAD

**Issue by fransbrain** [cloudybasement/fran.cool#39]
Can this link's visibility be optional pls? thonks

<img width="666" alt="Screen Shot 2022-10-24 at 19 40 20" src="https://user-images.githubusercontent.com/116001537/197590793-368c35a7-16d1-4616-895d-d8f8b09362b9.png">

**Comment by cloudybasement** [comment]
[if u no put a linky, no a linky will appears](https://fran.cool/works/professionalorganiserco/)
